### ISSUE TITLE
NullPointerException in JIComObjectImpl.call()

### ISSUE THREAD

**Issue by mstrd308** [ibh-systems/org.openscada#3]
Hello,

I've had the following issue in an old version of org.openscada.jinterop.core (1.1.0.v20130529) and I'd like to know if this is a known issue and if it has been fixed with any newer versions? The old repository is down, so I cannot see any history of the source. 

Please see stack trace below:

`WARNING: java.lang.NullPointerException
        at org.jinterop.dcom.core.JIComObjectImpl.call(JIComObjectImpl.java:295)
        at org.jinterop.dcom.core.JIComObjectImpl.call(JIComObjectImpl.java:161)
        at org.openscada.opc.dcom.common.impl.Helper.callRespectSFALSE(Helper.java:41)
        at org.openscada.opc.dcom.da.impl.OPCItemMgt.add(OPCItemMgt.java:114)
        at org.openscada.opc.lib.da.Group.addItems(Group.java:216)
        at org.openscada.opc.lib.da.Group.addItem(Group.java:132)
        at org.openscada.opc.lib.da.AccessBase.realizeItem(AccessBase.java:230)
        at org.openscada.opc.lib.da.AccessBase.addItem(AccessBase.java:165)`

Thanks for any info.

**Comment by mstrd308** [comment]
@CptMauli any info on this? This is still actual
